### ISSUE TITLE
Program was killed after 5 seconds, even with the specified "--timeout 120" in the command line

### ISSUE THREAD

**Issue by JialuZhang** [iradicek/clara#31]
$ clara repair odd_even_examples/src0_simple.c odd_even_examples/src1_simple.c --entryfnc main --args "[[3, [4,5,6]]]" --timeout 120 --verbose 1
[debug] Guessed language: c
[debug] Reading and parsing source file 'odd_even_examples/src0_simple.c'
[debug] Reading and parsing source file 'odd_even_examples/src1_simple.c'
Error occured: Timeout (5.000)
Traceback (most recent call last):
  File "/home/jz598/.local/bin/clara", line 450, in <module>
    clara.main()
  File "/home/jz598/.local/bin/clara", line 188, in main
    self.repair()
  File "/home/jz598/.local/bin/clara", line 294, in repair
    r = R.repair(self.models[0], self.models[1], self.inter,
  File "/home/jz598/.local/lib/python3.8/site-packages/clara/repair.py", line 146, in repair
    self.trace = self.gettrace(P, inter, ins, args, entryfnc)
  File "/home/jz598/.local/lib/python3.8/site-packages/clara/repair.py", line 118, in gettrace
    t = I.run(P, ins=i, args=a)
  File "/home/jz598/.local/lib/python3.8/site-packages/clara/interpreter.py", line 99, in run
    res = self.execute(fnc, mem)
  File "/home/jz598/.local/lib/python3.8/site-packages/clara/interpreter.py", line 119, in execute
    return meth(obj, mem)
  File "/home/jz598/.local/lib/python3.8/site-packages/clara/interpreter.py", line 135, in execute_Function
    val = self.execute(expr, mem)
  File "/home/jz598/.local/lib/python3.8/site-packages/clara/interpreter.py", line 110, in execute
    raise RuntimeErr(
clara.interpreter.RuntimeErr: Timeout (5.000)

Here are the two programs. 

$ cat odd_even_examples/src0.c
```
int main(int t, long long int n_a[])
{
long long int n;
while(t--)
{
n=n_a[t];
if(n%2==0)
printf ("No\n");
else
printf ("Yes\n");
}
return 0;
}
```
$ cat odd_even_examples/src1.c
```
int main(int t, long long int n_a[])
{
long long int n;
while(t--)
{
n=n_a[t];
if(n%2==0)
printf ("Yes\n");
else
printf ("No\n");
}
return 0;
}
```

**Comment by iradicek** [comment]
Thank you for reporting this issue. The issue is not really in the timeout. The repair timeouts in executing the reference (`src0.c`) program, because there is a bug in translation to the internal model, due to which program ends up with an infinite loop. (The bug is in translation of `t--` in the loop condition). I will look into fixing this issue.
